# Generated by Django 5.2.12 on 2026-03-16 06:37

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_order_number_product_product_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_qr',
            field=models.ImageField(upload_to=core.utils.order_qr_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_qr',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.product_qr_path),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.store_logo_path),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_qr',
            field=models.ImageField(upload_to=core.utils.store_payment_qr_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.profile_photo_path),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='expires_at',
        ),
    ]
