# Generated by Django 5.2.12 on 2026-03-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartitem_unique_together_store_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='store_name',
        ),
    ]
