# Generated by Django 5.2.12 on 2026-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_store_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_pass',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
